# Generated by Django 5.1.1 on 2024-11-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shegarland', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shegarlandform',
            name='bal_lafa_bahi_tae',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shegarlandform',
            name='bal_lafa_hafe',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
    ]
