# Generated by Django 5.1.1 on 2024-11-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shegarland', '0002_alter_shegarlandform_bal_lafa_bahi_tae_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shegarlandform',
            name='Aanaa',
            field=models.CharField(choices=[('Abbaa Gadaa', 'Abbaa Gadaa'), ('wasarbii', 'wasarbii'), ('Tufaa munaa', 'Tufaa munaa'), ('A/M/Abbichuu', 'A/M/Abbichuu'), ('Eekkaa Daallee', 'Eekkaa Daallee'), ('Lagaa Dambal', 'Lagaa Dambal'), ('Ekkaa Sadeen', 'Ekkaa Sadeen'), ('Haroo Qullit', 'Haroo Qullit'), ('Dire_Sokkoruu', 'Dire Sokorruu'), ('Kuraa Jidda', 'Kuraa Jidda'), ('Galaan Arabsaa', 'Galaan Arabsaa'), ('Galaan Goraa', 'Galaan Goraa'), ('Faccee', 'Faccee'), ('Siidaa awaash', 'Siidaa awaash'), ('Galaan', 'Galaan'), ('Andoodee', 'Andoodee'), ('Mudaa Furii', 'Mudaa Furii'), ('Caffe karaabuu', 'Caffe karaabuu'), ('Gadaa Faajjii', 'Gadaa Faajjii'), ('Galaan Guddaa', 'Galaan Guddaa'), ('Lakkulee gejjaa', 'Lakkulee gejjaa'), ('Daalattii', 'Daalattii'), ('Wacacaa', 'Wacacaa'), ('Mogolee', 'Mogolee'), ('Caffee', 'Caffee'), ('M/gafarsaa', 'M/gafarsaa'), ('Nonnoo', 'Nonnoo'), ('Beeroo', 'Beeroo'), ('B/Kattaa', 'B/Kattaa'), ('L/kattaa', 'L/kattaa'), ('A/diimaa', 'A/diimaa'), ('G/burrayyuu', 'G/burrayyuu'), ('Egduu ilalaa', 'Egduu ilalaa'), ('Gujee', 'Gujee'), ('Koloboo', 'Koloboo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='shegarlandform',
            name='Kutaamagaalaa',
            field=models.CharField(choices=[('Sulultaa', 'Sulultaa'), ('M/Abbichuu', 'M/Abbichuu'), ('L/Xafoo L/Dadhii', 'L/Xafoo L/Dadhii'), ('K/Jiddaa', 'K/Jiddaa'), ('K/faccee', 'K/faccee'), ('Galaan', 'Galaan'), ('Furii', 'Furii'), ('G/Guddaa', 'G/Guddaa'), ('Sabbataa', 'Sabbataa'), ('M/Nonnoo', 'M/Nonnoo'), ('G/Gujee', 'G/Gujee'), ('Burrayyuu', 'Burrayyuu')], max_length=50),
        ),
        migrations.AlterField(
            model_name='shegarlandform',
            name='Ragaa_biroo',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='shegarlandform',
            name='guyya_qophae',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='shegarlandform',
            name='haala_beenya',
            field=models.CharField(choices=[('Bilisaa', 'Bilisaa'), ('Beenyaa kan qabu', 'Beenyaa kan qabu')], max_length=20),
        ),
        migrations.AlterField(
            model_name='shegarlandform',
            name='tajajila_iddo',
            field=models.CharField(choices=[('Adminstration/AD/', 'Adminstration/AD/'), ('Commercial/CO/', 'Commercial/CO/'), ('Eco_Tourism/RE-5/', 'Eco_Tourism/RE-5/'), ('Formal Green', 'Formal Green'), ('Recreational & Environmental/RE/', 'Recreational & Environmental/RE/'), ('Open Spaces and Sport Centers', 'Open Spaces and Sport Centers'), ('Pure Residence/R/', 'Pure Residence/R/'), ('Mixid Residence/R-2/', 'Mixid Residence/R-2/'), ('Manufacturing and Storage/P-1/', 'Manufacturing and Storage/P-1/'), ('Social Service/S/', 'Social Service/S/'), ('Special Function', 'Special Function'), ('Special residence', 'Special residence'), ('Transport', 'Transport'), ('Urban Agriculture/UA/', 'Urban Agriculture'), ('Logestic and Free Trade Zone', 'Logestic and Free Trade Zone'), ('River and Arteficial Lake', 'River and Arteficial Lake'), ('High Density Mixed Residence', 'High Density Mixed Residence')], max_length=60),
        ),
    ]
