# Generated by Django 5.1.1 on 2024-12-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shegarland', '0008_alter_shegarlandform_bal_lafa_bahi_tae_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shegarlandform',
            name='Aanaa',
            field=models.CharField(choices=[('Abbaa Gadaa', 'Abbaa Gadaa'), ('wasarbii', 'wasarbii'), ('Tufaa munaa', 'Tufaa munaa'), ('A/M/Abbichuu', 'A/M/Abbichuu'), ('Eekkaa Daallee', 'Eekkaa Daallee'), ('Lagaa Dambal', 'Lagaa Dambal'), ('Ekkaa Sadeen', 'Ekkaa Sadeen'), ('Haroo Qullit', 'Haroo Qullit'), ('Dire_Sokkoruu', 'Dire Sokorruu'), ('Kuraa Jidda', 'Kuraa Jidda'), ('Galaan Arabsaa', 'Galaan Arabsaa'), ('Waddeessa', 'Waddeessa'), ('Tulluu Dimtuu', 'Tulluu Dimtuu'), ('Siidaa awaash', 'Siidaa awaash'), ('Galaan', 'Galaan'), ('Andoodee', 'Andoodee'), ('Mudaa Furii', 'Mudaa Furii'), ('Caffe karaabuu', 'Caffe karaabuu'), ('Gadaa Faajjii', 'Gadaa Faajjii'), ('Galaan Guddaa', 'Galaan Guddaa'), ('Lakkulee gejjaa', 'Lakkulee gejjaa'), ('Daalattii', 'Daalattii'), ('Wacacaa', 'Wacacaa'), ('Mogolee', 'Mogolee'), ('Caffee', 'Caffee'), ('M/gafarsaa', 'M/gafarsaa'), ('Nonnoo', 'Nonnoo'), ('Beeroo', 'Beeroo'), ('B/Kattaa', 'B/Kattaa'), ('L/kattaa', 'L/kattaa'), ('A/diimaa', 'A/diimaa'), ('G/burrayyuu', 'G/burrayyuu'), ('Egduu ilalaa', 'Egduu ilalaa'), ('Gujee', 'Gujee'), ('Koloboo', 'Koloboo')], max_length=50),
        ),
    ]
